"""Standalone, read-only Guardian Diagnostics presentation."""
from __future__ import annotations

from html import escape


def render_guardian_diagnostics_html(*, api_path: str = "api/diagnostics",
                                     modules_path: str = "./") -> str:
    api = escape(api_path.rstrip("/"), quote=True)
    modules = escape(modules_path, quote=True)
    return r'''<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Guardian Diagnostics</title><style>
:root{color-scheme:light dark;--blue:#0d47a1;--accent:#1976d2;--line:#8884;--panel:var(--card-background-color,#fff);--muted:var(--secondary-text-color,#667085)}*{box-sizing:border-box}body{margin:0;font:15px/1.48 system-ui;background:var(--primary-background-color,#f5f6f8);color:var(--primary-text-color,#202124)}header{background:var(--blue);color:#fff;padding:20px clamp(16px,4vw,42px)}header h1{margin:0;font-size:clamp(24px,4vw,34px)}header p{margin:5px 0 0;opacity:.9}header a{color:#fff}.page{max-width:1180px;margin:auto;padding:20px}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.layout{display:grid;grid-template-columns:minmax(0,2fr) minmax(260px,1fr);gap:16px;margin-top:16px}.card{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:16px;box-shadow:0 2px 8px #0001}.metric{font-size:25px;font-weight:700}.muted{color:var(--muted)}.quality{border-left:5px solid #607d8b}.quality.partial{border-left-color:#e0a000}.quality.complete{border-left-color:#1976d2}.status{font-weight:700;text-transform:uppercase;letter-spacing:.03em}.observations{padding-left:20px}.day{width:100%;text-align:left;padding:11px;border:0;border-bottom:1px solid var(--line);background:transparent;color:inherit;cursor:pointer}.day:hover,.day.active{background:#1976d218}select{width:100%;padding:10px;border:1px solid var(--line);border-radius:8px;background:var(--panel);color:inherit}.module{margin-top:12px}.facts{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px 16px}.fact b{display:block}.tag{display:inline-block;padding:2px 7px;border-radius:999px;background:#1976d220;margin:2px}.help summary,.evidence summary{cursor:pointer;font-weight:700}.notice{padding:10px;border-radius:8px;background:#e0a00020}.error{background:#c6282820}.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:8px;border-bottom:1px solid var(--line);white-space:nowrap}@media(max-width:800px){.grid{grid-template-columns:repeat(2,1fr)}.layout{grid-template-columns:1fr}.facts{grid-template-columns:1fr}}@media(max-width:460px){.grid{grid-template-columns:1fr}.page{padding:12px}}
</style></head><body><header><h1>Guardian Diagnostics</h1><p>Automatische Auswertung abgeschlossener Betriebstage</p><a href="__MODULES__">Zurück zu Guardian Maintenance</a></header><main class="page"><section id="cards" class="grid" aria-label="Gesamtübersicht"></section><div class="layout"><div><section class="card"><h2>Wichtige Beobachtungen</h2><ul id="observations" class="observations"></ul></section><section id="detail" class="card" style="margin-top:16px"><h2>Tagesdiagnose</h2><p class="muted">Noch kein Diagnosetag ausgewählt.</p></section></div><aside><section class="card"><h2>Tagesdiagnosen</h2><label for="day-select">Datumsauswahl</label><select id="day-select" aria-label="Diagnosetag"></select><div id="days"></div></section></aside></div><details class="card help" style="margin-top:16px"><summary>Info und Hilfe</summary><h2>Was Guardian Diagnostics zeigt</h2><p>Daily Diagnostics ist eine deterministische Auswertung bereits gespeicherter Evidence für abgeschlossene Guardian-Tage. Evidence bedeutet reproduzierbare Beobachtung. Eine zeitliche oder statistische Korrelation belegt noch keine Ursache; „Kausalität nicht bestimmt“ macht diese Grenze ausdrücklich sichtbar. Dies ist keine KI-Auswertung.</p><p><b>complete</b>: vollständig gemäß vorhandener Komponenten ausgewertet. <b>partial</b>: Datenlage teilweise, Interpretation eingeschränkt. <b>failed</b>: kein gültiges Tagesresultat; dies ist ein Analysefehler und kein Batteriezustand.</p><p><b>CCL</b> ist das vom adressierten BMS gemeldete zulässige Ladestromlimit, <b>DCL</b> das Entladestromlimit. Ein Limit von 0 A kann trotz aktivem Enable beobachtet werden; Enable und Zahlenlimit sind getrennte Protokollinformationen. Ein Peer-Vergleich setzt einen Modulwert ins Verhältnis zu gleichzeitig beobachteten Modulen, ohne einen festen Normalwert zu definieren.</p><p><b>Management Coverage</b> ist die gap-qualifizierte Beobachtungszeit. Der Duty Cycle ist gap-qualifizierte Restriktionsdauer geteilt durch diese Coverage. Die Endpoint-Dauer misst dagegen den Abstand zwischen beobachtetem Beginn und Recovery und kann daher größer sein.</p><p><b>Lowest Cell</b> bezeichnet die niedrigste Zelle im zeitlich zugeordneten Zellkontext. Der 0x44-Kontext zeigt nur rohe, zeitlich korrelierte Byteübergänge. Ihre fachliche Bedeutung ist derzeit nicht dokumentiert; Guardian bezeichnet sie weder als Protection, MOSFET, Fault noch Shutdown.</p></details></main><script>
const API='__API__';const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const n=(v,d=2)=>v==null?'—':Number(v).toLocaleString('de-DE',{maximumFractionDigits:d});const pct=v=>v==null?'—':n(100*Number(v),2)+' %';const dateDE=v=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(v||''))return '—';const [y,m,d]=v.split('-');return `${d}.${m}.${y}`};
async function get(path){const response=await fetch(`${API}/${path}`,{method:'GET',headers:{Accept:'application/json'}}),body=await response.json();if(!response.ok)throw new Error(body.error?.message||'Diagnosedaten nicht verfügbar');return body}
function windowCard(label,w){return `<article class="card"><div class="muted">${label}</div><div class="metric">${w.available_days} Tage</div><div>${w.management_event_count} Managementereignisse</div><small>${w.complete_days} vollständig · ${w.partial_days} teilweise${w.history_sufficient?'':' · noch nicht genügend Daten'}</small></article>`}
function renderOverview(o){const latest=o.latest_date?dateDE(o.latest_date):'Kein Ergebnis',quality=o.data_quality||{};document.getElementById('cards').innerHTML=`<article class="card quality ${esc(o.latest_status||'none')}"><div class="muted">Letzte Tagesdiagnose</div><div class="metric">${esc(latest)}</div><div class="status">${esc(quality.label||'Nicht genügend Historie')}</div></article>${windowCard('7 Tage',o.windows['7d'])}${windowCard('30 Tage',o.windows['30d'])}<article class="card"><div class="muted">Datenqualität</div><div class="metric">${o.available_day_count}</div><div>analysierte Tage</div><small>Aktive Komponente: ${esc((o.active_component_labels||[]).join(', '))}</small></article>`;const list=document.getElementById('observations');list.innerHTML=(o.important_observations||[]).map(x=>`<li>${esc(x.text)}</li>`).join('')||'<li>Noch nicht genügend Daten.</li>'}
function renderDays(data){const select=document.getElementById('day-select'),list=document.getElementById('days');select.innerHTML='';list.innerHTML='';for(const d of data.days){select.insertAdjacentHTML('beforeend',`<option value="${esc(d.date)}">${dateDE(d.date)} · ${esc(d.quality.label)}</option>`);list.insertAdjacentHTML('beforeend',`<button class="day" data-date="${esc(d.date)}"><b>${dateDE(d.date)}</b><br><span class="muted">${esc(d.quality.label)} · ${d.event_count} Ereignisse</span></button>`)}if(!data.days.length){select.innerHTML='<option>Keine Tagesdiagnosen vorhanden</option>';list.innerHTML='<p class="muted">Nicht genügend Historie.</p>';return}select.onchange=()=>loadDay(select.value);list.onclick=e=>{const button=e.target.closest('[data-date]');if(button){select.value=button.dataset.date;loadDay(button.dataset.date)}};loadDay(data.days[0].date)}
function fact(label,value){return `<div class="fact"><b>${esc(label)}</b><span>${esc(value)}</span></div>`}
function moduleCard(a){const serial=esc(a.physical_serial||'Seriennummer unbekannt'),positions=(a.positions_at_time||[]).length?`Modul/Position ${a.positions_at_time.map(esc).join(', ')} · `:'',transition=a.dominant_0x44_transition||'nicht verfügbar',enable=a.charge_enable==null?'nicht im Tagesaggregat':(a.charge_enable?'ENABLED':'STOP REQUEST');return `<article class="card module"><h3>${positions}Seriennummer ${serial}</h3><div class="facts">${fact('CCL Reductions',a.ccl_reduction_event_count??0)}${fact('CCL Zero',a.ccl_zero_event_count??0)}${fact('CCL Minimum',a.ccl_min_a==null?'nicht verfügbar':n(a.ccl_min_a)+' A')}${fact('CCL Median',a.ccl_median_a==null?'nicht verfügbar':n(a.ccl_median_a)+' A')}${fact('CCL beobachtet',a.ccl_observed_a==null?'nicht als Einzelwert persistiert':n(a.ccl_observed_a)+' A')}${fact('CCL Peer-Median',a.ccl_peer_median_a==null?'nicht verfügbar':n(a.ccl_peer_median_a)+' A')}${fact('CCL Peer-Abweichung',a.ccl_peer_deviation_a==null?'nicht verfügbar':n(a.ccl_peer_deviation_a)+' A')}${fact('CCL relativ',a.relative_ccl_ratio==null?(a.peer_relative_ccl_min_ratio==null?'nicht verfügbar':pct(a.peer_relative_ccl_min_ratio)):pct(a.relative_ccl_ratio))}${fact('Charge Enable (separate Evidence)',enable)}${fact('DCL Reductions',a.dcl_reduction_event_count??0)}${fact('DCL Zero',a.dcl_zero_event_count??a.dcl_zero_count??0)}${fact('DCL Zero trotz Enable',a.dcl_zero_despite_enable_count??0)}${fact('DCL Zero Duty Cycle',pct(a.dcl_zero_duty_cycle))}${fact('Management Coverage',pct(a.management_coverage_ratio_of_day))}${fact('Dominante Lowest Cell',a.dominant_lowest_cell?`Zelle ${a.dominant_lowest_cell} · ${pct(a.dominant_lowest_ratio)}`:'Kein ausreichender Zellkontext verfügbar')}${fact('Minimum Cell',a.minimum_cell_before_dcl_zero_mv==null?'nicht verfügbar':n(a.minimum_cell_before_dcl_zero_mv,0)+' mV')}${fact('Maximum Spread',a.max_spread_before_dcl_zero_mv==null?'nicht verfügbar':n(a.max_spread_before_dcl_zero_mv,0)+' mV')}${fact('Stärkster Entladestrom davor',a.max_discharge_current_before_a==null?'nicht verfügbar':n(a.max_discharge_current_before_a,3)+' A')}</div><details class="evidence"><summary>Technische Evidence</summary><p>Wiederkehrendes rohes BMS-Muster: <code>${esc(transition)}</code> · ${pct(a.dominant_0x44_ratio)} der DCL-Zero-Ereignisse.</p><p>Endpoint-Dauer und gap-qualifizierte Restriktionsdauer sind getrennte Werte. Duty Cycle = gap-qualifizierte Dauer / Management Coverage.</p><p><b>Kausalität: nicht bestimmt.</b> Guardian zeigt ausschließlich beobachtete Zusammenhänge.</p></details></article>`}
async function loadDay(day){const box=document.getElementById('detail');try{const d=await get(`daily/${encodeURIComponent(day)}`),q=d.quality||{},summary=d.summary||{},aggregates=d.bms_management?.aggregates||[];document.querySelectorAll('.day').forEach(x=>x.classList.toggle('active',x.dataset.date===day));box.innerHTML=`<h2>${dateDE(d.date)} · Tagesdiagnose</h2><p class="status">${esc(q.label)}</p>${q.interpretation_limited?'<p class="notice">Datenlage teilweise – Interpretation eingeschränkt.</p>':''}<p><b>Analysierte Quellen:</b> ${esc(Object.entries(d.sources||{}).filter(([,v])=>!v.missing).map(([k])=>k).join(', ')||'nicht verfügbar')}</p><p><b>Aktive deterministische Diagnosekomponente:</b> BMS Management Evidence</p><ul>${(summary.important_observations||[]).map(x=>`<li>${esc(x.text)}</li>`).join('')}</ul><p><b>Handlungshinweis:</b> ${esc(summary.recommendation)}</p>${aggregates.map(moduleCard).join('')||'<p>Keine BMS-Management-Aggregate für diesen Tag vorhanden.</p>'}` }catch(error){box.innerHTML=`<h2>Tagesdiagnose</h2><p class="notice error">${esc(error.message)}</p>`}}
Promise.all([get('overview'),get('days')]).then(([o,d])=>{renderOverview(o);renderDays(d)}).catch(error=>{document.getElementById('observations').innerHTML=`<li>${esc(error.message)}</li>`});
</script></body></html>'''.replace("__API__", api).replace("__MODULES__", modules)
