"""Module identity and documentary position-history UI."""
from html import escape

from guardian_header import render_guardian_header


def render_module_information_html(*, configuration_path: str, maintenance_path: str,
                                   timeline_path: str = "timeline",
                                   history_path: str = "history") -> str:
    page = r'''<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Guardian Battery · Modulinformationen</title><style>
:root{color-scheme:light dark;--blue:#0d47a1;--accent:#1976d2;--line:#8884}*{box-sizing:border-box}body{margin:0;font:15px/1.45 system-ui;background:var(--primary-background-color,#f5f6f8);color:var(--primary-text-color,#202124)}header{background:var(--blue);color:#fff;padding:18px clamp(16px,4vw,34px)}nav{display:flex;gap:8px;flex-wrap:wrap}nav a{color:#fff;text-decoration:none;padding:8px 12px;border:1px solid #ffffff66;border-radius:8px}main{max-width:1180px;margin:auto;padding:16px}section{background:var(--card-background-color,#fff);padding:16px;border-radius:12px;margin-bottom:14px;box-shadow:0 1px 5px #0002}.table-wrap{overflow-x:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:9px;border-bottom:1px solid var(--line);white-space:nowrap}.matrix th,.matrix td{text-align:center}.matrix th:first-child,.matrix td:first-child{text-align:left;position:sticky;left:0;background:var(--card-background-color,#fff);font-weight:700}.matrix .current{background:#1976d218;font-weight:700}.alert{padding:10px;background:#ef6c0018;border-left:4px solid #ef6c00;margin:8px 0}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}label{display:flex;flex-direction:column;gap:4px;font-weight:650}input,button{font:inherit;padding:9px;border:1px solid #8888;border-radius:7px;background:transparent;color:inherit}button{background:var(--accent);color:#fff;border:0;cursor:pointer}.secondary{background:transparent;color:inherit;border:1px solid #8888}@media(max-width:700px){.grid{grid-template-columns:1fr}table{font-size:13px}main{padding:10px}}
</style></head><body>__HEADER__<main>
<section id="module-information"><h2>Aktuelle Zuordnung</h2><p>Die Seriennummer identifiziert das physische Modul dauerhaft. Die Position beschreibt nur seinen Platz im Stack zu einem bestimmten Zeitpunkt.</p><div id="divergence"></div><div class="table-wrap"><table><thead><tr><th>Position</th><th>Dokumentierte Seriennummer</th><th>Aktuell beobachtet</th></tr></thead><tbody id="current"></tbody></table></div></section>
<section id="stack-and-modules"><h2>Stack-Positionshistorie</h2><p>Jede Datumsspalte ist eine bestätigte Änderung und zeigt den vollständigen Stack. Neustarts und unveränderte Lesungen erzeugen keine neue Spalte.</p><div class="table-wrap"><table class="matrix"><thead id="matrix-head"></thead><tbody id="matrix-body"></tbody></table></div><p id="older-wrap" hidden><button id="older" class="secondary" type="button">Ältere Änderungen anzeigen</button></p></section>
<section><h2>Positionsänderung dokumentieren</h2><p>Jeder Eintrag ist ein vollständiger, unveränderlicher Stack-Snapshot und benötigt ein Maintenance Event.</p><form id="form"><div class="grid"><label>Wirksam ab<input id="effective" type="datetime-local" required></label><label>Maintenance Event ID<input id="maintenance" pattern="MEV-.*" required></label><span></span><div id="positions" class="grid" style="grid-column:1/-1"></div></div><p><button>Snapshot append-only speichern</button></p></form><div id="message" role="status"></div></section>
<section><h2>Änderungsdetails</h2><div class="table-wrap"><table><thead><tr><th>Wirksam ab</th><th>Vollständige Zuordnung</th><th>Maintenance Event</th></tr></thead><tbody id="history"></tbody></table></div></section>
</main><script>
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const local=v=>v?new Intl.DateTimeFormat('de-DE',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—';
const shortDate=v=>new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',year:'2-digit'}).format(new Date(v));
let latest=null,allSnapshots=[],matrixSnapshots=[],matrixLimit=20;
function maintenanceHref(id){return `maintenance?event_id=${encodeURIComponent(id)}&return=${encodeURIComponent(location.pathname+location.search+location.hash)}`;}function renderMatrix(){const current=allSnapshots.at(-1),history=matrixSnapshots.filter(item=>!current||item.position_history_id!==current.position_history_id).slice().reverse().slice(0,matrixLimit),head=document.getElementById('matrix-head'),body=document.getElementById('matrix-body');head.innerHTML='<tr><th>Position</th>'+history.map(item=>`<th title="${esc(local(item.effective_at))}"><a href="${maintenanceHref(item.maintenance_event_id)}">${esc(shortDate(item.effective_at))}</a></th>`).join('')+'</tr>';body.innerHTML='';for(let position=6;position>=1;position--){const cells=history.map(item=>`<td>${esc(item.positions[position]||'leer')}</td>`).join('');body.insertAdjacentHTML('beforeend',`<tr><td>Position ${position}</td>${cells}</tr>`)}document.getElementById('older-wrap').hidden=history.length>=Math.max(0,matrixSnapshots.length-(current?1:0));}
function init(){const positions=document.getElementById('positions');for(let number=1;number<=6;number++)positions.insertAdjacentHTML('beforeend',`<label>Position ${number} · Seriennummer<input id="p${number}" maxlength="200" placeholder="unbekannt / leer"></label>`);const date=new Date(),pad=n=>String(n).padStart(2,'0');document.getElementById('effective').value=`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;load();}
async function load(){const [all,current]=await Promise.all([fetch('api/position-history').then(response=>response.json()),fetch('api/position-history/current').then(response=>response.json())]);allSnapshots=all.snapshots||[];matrixSnapshots=allSnapshots.filter((item,index,array)=>index===0||JSON.stringify(item.positions)!==JSON.stringify(array[index-1].positions));latest=current.snapshot?.position_history_id??null;const rows=document.getElementById('current');rows.innerHTML='';for(let number=6;number>=1;number--)rows.insertAdjacentHTML('beforeend',`<tr><td>${number}</td><td>${esc(current.snapshot?.positions?.[number]||'Seriennummer unbekannt')}</td><td>${esc(current.observed?.[number]||'nicht verfügbar')}</td></tr>`);document.getElementById('divergence').innerHTML=current.divergence.length?`<div class="alert">Dokumentation und aktuelle stabile Beobachtung weichen an ${current.divergence.length} Position(en) ab.</div>`:'';renderMatrix();const history=document.getElementById('history');history.innerHTML='';for(const item of [...allSnapshots].reverse()){const assignment=Object.entries(item.positions).map(([position,serial])=>`P${position}: ${serial||'leer'}`).join(' · ');history.insertAdjacentHTML('beforeend',`<tr><td title="${esc(item.effective_at)}">${esc(local(item.effective_at))}</td><td>${esc(assignment)}</td><td><a href="${maintenanceHref(item.maintenance_event_id)}">${esc(item.maintenance_event_id)}</a></td></tr>`);}}
document.getElementById('older').onclick=()=>{matrixLimit+=20;renderMatrix()};
document.getElementById('form').onsubmit=async event=>{event.preventDefault();const positions={};for(let number=1;number<=6;number++)positions[number]=document.getElementById('p'+number).value.trim()||null;const body={effective_at:new Date(document.getElementById('effective').value).toISOString(),maintenance_event_id:document.getElementById('maintenance').value.trim(),positions,expected_latest_snapshot_id:latest},response=await fetch('api/position-history',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await response.json();document.getElementById('message').textContent=response.ok?'Snapshot gespeichert.':data.error?.message||'Fehler';if(response.ok)load();};
document.addEventListener('DOMContentLoaded',init);
</script></body></html>'''
    paths = {"modules": "./", "configuration": configuration_path,
             "maintenance": maintenance_path, "timeline": timeline_path,
             "history": history_path}
    return page.replace("__HEADER__", render_guardian_header(active="modules", paths=paths))
