"""Module identity and documentary position-history UI."""
from html import escape

def render_module_information_html(*, configuration_path: str, maintenance_path: str) -> str:
    return f'''<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Guardian Battery · Modulinformationen</title><style>
:root{{color-scheme:light dark;--blue:#0d47a1;--accent:#1976d2;--line:#8884}}*{{box-sizing:border-box}}body{{margin:0;font:15px/1.45 system-ui;background:var(--primary-background-color,#f5f6f8);color:var(--primary-text-color,#202124)}}header{{background:var(--blue);color:#fff;padding:18px clamp(16px,4vw,34px)}}nav{{display:flex;gap:8px;flex-wrap:wrap}}nav a{{color:#fff;text-decoration:none;padding:8px 12px;border:1px solid #ffffff66;border-radius:8px}}main{{max-width:1180px;margin:auto;padding:16px}}section{{background:var(--card-background-color,#fff);padding:16px;border-radius:12px;margin-bottom:14px;box-shadow:0 1px 5px #0002}}table{{width:100%;border-collapse:collapse}}th,td{{text-align:left;padding:9px;border-bottom:1px solid var(--line)}}.alert{{padding:10px;background:#ef6c0018;border-left:4px solid #ef6c00;margin:8px 0}}.grid{{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}}label{{display:flex;flex-direction:column;gap:4px;font-weight:650}}input,button{{font:inherit;padding:9px;border:1px solid #8888;border-radius:7px;background:transparent;color:inherit}}button{{background:var(--accent);color:#fff;border:0;cursor:pointer}}@media(max-width:700px){{.grid{{grid-template-columns:1fr}}table{{font-size:13px}}main{{padding:10px}}}}
</style></head><body><header><h1>Modulinformationen</h1><nav><a href="{escape(configuration_path,quote=True)}">Konfiguration</a><a href="{escape(maintenance_path,quote=True)}">Maintenance-Logbuch</a></nav></header><main>
<section><h2>Aktuelle Zuordnung</h2><p>Beobachtete Seriennummern sind technische Momentaufnahmen. Erst eine dokumentierte Änderung mit Maintenance Event wird Teil der historischen Wahrheit.</p><div id="divergence"></div><table><thead><tr><th>Position</th><th>Dokumentierte Seriennummer</th><th>Aktuell beobachtet</th></tr></thead><tbody id="current"></tbody></table></section>
<section><h2>Positionsänderung dokumentieren</h2><p>Jeder Eintrag ist ein vollständiger Stack-Snapshot und unveränderlich. Auch die Initialerfassung benötigt ein Maintenance Event.</p><form id="form"><div class="grid"><label>Wirksam ab<input id="effective" type="datetime-local" required></label><label>Maintenance Event ID<input id="maintenance" pattern="MEV-.*" required></label><span></span><div id="positions" class="grid" style="grid-column:1/-1"></div></div><p><button>Snapshot append-only speichern</button></p></form><div id="message" role="status"></div></section>
<section><h2>Positionshistorie</h2><table><thead><tr><th>Wirksam ab</th><th>Zuordnung</th><th>Maintenance Event</th></tr></thead><tbody id="history"></tbody></table></section></main><script>
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}}[c]));let latest=null;const local=v=>v?new Intl.DateTimeFormat('de-DE',{{dateStyle:'medium',timeStyle:'short'}}).format(new Date(v)):'—';
function init(){{const p=document.getElementById('positions');for(let n=1;n<=6;n++)p.insertAdjacentHTML('beforeend',`<label>Position ${{n}} · Seriennummer<input id="p${{n}}" maxlength="200" placeholder="unbekannt / leer"></label>`);const d=new Date(),z=n=>String(n).padStart(2,'0');document.getElementById('effective').value=`${{d.getFullYear()}}-${{z(d.getMonth()+1)}}-${{z(d.getDate())}}T${{z(d.getHours())}}:${{z(d.getMinutes())}}`;load();}}
async function load(){{const [all,current]=await Promise.all([fetch('api/position-history').then(r=>r.json()),fetch('api/position-history/current').then(r=>r.json())]);latest=current.snapshot?.position_history_id??null;const rows=document.getElementById('current');rows.innerHTML='';for(let n=1;n<=6;n++)rows.insertAdjacentHTML('beforeend',`<tr><td>${{n}}</td><td>${{esc(current.snapshot?.positions?.[n]||'Seriennummer unbekannt')}}</td><td>${{esc(current.observed?.[n]||'nicht verfügbar')}}</td></tr>`);document.getElementById('divergence').innerHTML=current.divergence.length?`<div class="alert">Dokumentation und aktuelle Beobachtung weichen an ${{current.divergence.length}} Position(en) ab. Die Historie wird nicht automatisch verändert.</div>`:'';const history=document.getElementById('history');history.innerHTML='';for(const item of [...all.snapshots].reverse()){{const assignment=Object.entries(item.positions).map(([p,s])=>`P${{p}}: ${{s||'unbekannt'}}`).join(' · ');history.insertAdjacentHTML('beforeend',`<tr><td>${{local(item.effective_at)}}</td><td>${{esc(assignment)}}</td><td><a href="maintenance?event_id=${{encodeURIComponent(item.maintenance_event_id)}}">${{esc(item.maintenance_event_id)}}</a></td></tr>`);}}}}
document.getElementById('form').onsubmit=async e=>{{e.preventDefault();const positions={{}};for(let n=1;n<=6;n++)positions[n]=document.getElementById('p'+n).value.trim()||null;const body={{effective_at:new Date(document.getElementById('effective').value).toISOString(),maintenance_event_id:document.getElementById('maintenance').value.trim(),positions,expected_latest_snapshot_id:latest}};const r=await fetch('api/position-history',{{method:'POST',headers:{{'Content-Type':'application/json'}},body:JSON.stringify(body)}}),data=await r.json();document.getElementById('message').textContent=r.ok?'Snapshot gespeichert.':data.error?.message||'Fehler';if(r.ok)load();}};document.addEventListener('DOMContentLoaded',init);
</script></body></html>'''
