

# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  packages: !include_dir_named packages

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
lovelace:
  resource_mode: yaml
  resources:
    - url: /local/guardian-collapsible-card.js?v=2
      type: module
  dashboards:
    guardian-cell-diagnostics:
      mode: yaml
      title: Zelldiagnostik
      icon: mdi:battery
      show_in_sidebar: true
      filename: dashboards/guardian_cell_diagnostics.yaml
    guardian-module-information:
      mode: yaml
      title: Modul-Informationen
      icon: mdi:information-outline
      show_in_sidebar: true
      filename: dashboards/guardian_module_information.yaml
